---
- hosts: webservers
  gather_facts: True
  become: yes
  become_method: sudo

  tasks:
    - name: Install Apache
      package:
        name: httpd
        state: present

    - name: Start Apache service
      service:
        name: httpd
        state: started

    - name: Add custom welcome page
      template:
        src: ../templates/index.html.j2
        dest: /var/www/html/index.html

    - name: Restart Apache
      service:
        name: httpd
        state: restarted
