---
- name: Stop and remove Apache
  hosts: webservers
  gather_facts: True
  become: yes
  become_method: sudo

  tasks:
    - name: Stop Apache
      service:
        name: httpd
        state: stopped
      ignore_errors: true

    - name: Remove www directory
      file:
        path: /var/www/
        state: absent
      ignore_errors: true

    - name: Remove Apache
      package:
        name: httpd
        state: absent
      ignore_errors: true
