---
- name: Stop and remove Apache
  hosts: webservers
  gather_facts: true
  become: yes
  become_method: sudo

  tasks:
    # Service module is not idempotent
    # So "ignore_errors" is needed to not fail out if httpd doesn't exist
    - name: Stop Apache
      service:
        name: httpd
        state: stopped
      ignore_errors: true

    - name: Remove www directory
      file:
        path: /var/www/
        state: absent

    - name: Remove created test directory and file
      file:
        path: /home/vagrant/test/
        state: absent

    - name: Remove Apache
      package:
        name: httpd
        state: absent
